from django.core.management.base import BaseCommand

from core.models import PortalInformacao, Projeto


class Command(BaseCommand):
    help = "Cria/atualiza registros iniciais do portal de forma idempotente."

    def handle(self, *args, **options):
        defaults = [
            {
                "secao": "PRESTACAO",
                "titulo": "Ofício de Entrega da Prestação de Contas",
                "descricao": "Documento oficial de entrega da prestação de contas do Instituto Meio do Mundo.",
                "link": "/static/docs/oficio-de-entrega-da-prestacao-de-contas.pdf",
                "ordem": 1,
                "ativo": True,
            },
            {
                "secao": "PRESTACAO",
                "titulo": "Termo de Fomento Assinado - Instituto Meio do Mundo",
                "descricao": "Termo de Fomento assinado para acompanhamento e transparência.",
                "link": "/static/docs/termo-de-fomento-assinado-instituto-meio-do-mundo.pdf",
                "ordem": 2,
                "ativo": True,
            },

            {
                "secao": "PRESTACAO",
                "titulo": "Relatório de Execução - Conexão Amazônia",
                "descricao": "Relatório de execução do projeto Conexão Amazônia.",
                "link": "/static/docs/relatorio-execucao-conexao-amazonia.pdf",
                "ordem": 3,
                "ativo": True,
            },
            {
                "secao": "PRESTACAO",
                "titulo": "Relatório de Execução - Corrida da Visibilidade Feminina",
                "descricao": "Relatório de execução do projeto Corrida da Visibilidade Feminina.",
                "link": "/static/docs/relatorio-execucao-corrida-visibilidade-feminina.pdf",
                "ordem": 4,
                "ativo": True,
            },
            {
                "secao": "PRESTACAO",
                "titulo": "Relatório de Execução - Corrida da Polícia Civil",
                "descricao": "Relatório de execução do projeto Corrida da Polícia Civil.",
                "link": "/static/docs/relatorio-execucao-corrida-policia-civil.pdf",
                "ordem": 5,
                "ativo": True,
            },
            {
                "secao": "PRESTACAO",
                "titulo": "Relatório de Execução - Corpus Christi Patrocínio",
                "descricao": "Relatório de execução do projeto Corpus Christi Patrocínio.",
                "link": "/static/docs/relatorio-execucao-corpus-cristi-patrocinio.pdf",
                "ordem": 6,
                "ativo": True,
            },
            {
                "secao": "PRESTACAO",
                "titulo": "Relatório de Execução - 7 de Setembro PM",
                "descricao": "Relatório de execução do projeto 7 de Setembro PM.",
                "link": "/static/docs/relatorio-execucao-7-de-setembro-pm.pdf",
                "ordem": 7,
                "ativo": True,
            },
            {
                "secao": "PRESTACAO",
                "titulo": "Relatório de Execução - Calçoene Verão",
                "descricao": "Relatório de execução do projeto Calçoene Verão.",
                "link": "/static/docs/relatorio-execucao-calcoene-verao.pdf",
                "ordem": 8,
                "ativo": True,
            },
            {
                "secao": "PRESTACAO",
                "titulo": "Relatório de Execução - 4 Cantos da Floresta",
                "descricao": "Relatório de execução do projeto 4 Cantos da Floresta.",
                "link": "/static/docs/relatorio-execucao-4-cantos-da-floresta.pdf",
                "ordem": 9,
                "ativo": True,
            },
            {
                "secao": "PRESTACAO",
                "titulo": "Relatório de Execução - Corrida do Servidor Público",
                "descricao": "Relatório de execução do projeto Corrida do Servidor Público.",
                "link": "/static/docs/relatorio-execucao-corrida-do-servidor-publico.pdf",
                "ordem": 10,
                "ativo": True,
            },
            {
                "secao": "POLITICAS",
                "titulo": "Lei Geral de Proteção de Dados (LGPD)",
                "descricao": "Lei no 13.709/2018 (LGPD) - proteção de dados pessoais.",
                "link": "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/L13709.htm",
                "ordem": 3,
                "ativo": True,
            },
            {
                "secao": "POLITICAS",
                "titulo": "Lei de Acesso à Informação (LAI)",
                "descricao": "Lei no 12.527/2011 - acesso à informação pública.",
                "link": "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm",
                "ordem": 4,
                "ativo": True,
            },
        ]

        created = 0
        updated = 0
        for item in defaults:
            obj, was_created = PortalInformacao.objects.update_or_create(
                secao=item["secao"],
                titulo=item["titulo"],
                defaults=item,
            )
            if was_created:
                created += 1
            else:
                updated += 1
            self.stdout.write(f"OK: {obj.titulo}")

        self.stdout.write(
            self.style.SUCCESS(f"Seed concluído. Criados: {created}. Atualizados: {updated}."),
        )

        projetos = [
            {
                "titulo": "I CORRIDA DO SERVIDOR PÚBLICO DO ESTADO DO AMAPÁ",
                "subtitulo": "027/2025 – SEDEL",
                "status": "EM_ANDAMENTO",
                "icone": "🏃",
                "valor": "R$ 700.000,00",
                "instrumento": "027/2025 – SEDEL",
                "recurso_financeiro": "R$ 700.000,00",
                "fonte_recurso_estadual": "500",
                "fonte_recurso_federal": "N/S",
                "autoria_emenda": "Emenda Parlamentar Impositiva I0371 – Dep. Rodolfo Vale (R$ 200.000,00) + Tesouro Estadual (R$ 500.000,00)",
                "nome_projeto": "",
                "valor_repassado": "",
                "valor_global": "R$ 700.000,00",
                "objeto": 'Execução do Projeto "CORRIDA DO SERVIDOR PÚBLICO DO ESTADO DO AMAPÁ", incluindo pré-produção, produção e pós-produção do evento esportivo para 4.000 participantes, com percursos de 3 km, 5 km e 7 km, premiações e estrutura geral necessária.',
                "data_inicio": "28/10/2025",
                "data_finalizacao": "28/01/2026",
                "justificativa": "Promover esporte, lazer, qualidade de vida e integração social por meio da realização da Corrida do Servidor Público, incentivando práticas saudáveis e fortalecendo políticas públicas voltadas ao esporte no Estado do Amapá.",
                "dados_orcamentarios": "UG: SEDEL – Secretaria de Estado do Desporto e Lazer · Programa: 27.812.0016 · Projeto/Atividade/Ação: 2239 – Apoiar a prática do esporte para toda a vida de jovens e adultos · Elemento de Despesa: 335041 · Fonte: 500 · Valor Total: R$ 700.000,00 · Origem: Emenda Impositiva I0371 (R$ 200.000,00) + Tesouro Estadual (R$ 500.000,00)",
                "documento_link": "https://institutomeiodomundo.org/transparencia/wp-content/uploads/2025/12/FOMENTO-No-027-2025-IMM-CORRIDA-DO-SERVIDOR-assinado.pdf",
                "documento_label": "⬇️ FOMENTO Nº 027/2025 – IMM – CORRIDA DO SERVIDOR (PDF)",
                "ordem": 1,
            },
            {
                "titulo": "PROJETO DESFILE DA INDEPENDÊNCIA 2025",
                "subtitulo": "001/2025 – PMAP",
                "status": "EM_ANDAMENTO",
                "icone": "🎖️",
                "valor": "R$ 1.291.050,00",
                "instrumento": "001/2025 – PMAP",
                "recurso_financeiro": "R$ 1.291.050,00",
                "fonte_recurso_estadual": "500",
                "fonte_recurso_federal": "N/S",
                "autoria_emenda": "Dispensa de Chamamento Público – Processo Administrativo nº 0336/2025/CMDO/PMAP, Parecer Jurídico nº 469/2025 – GAB/PGE/AP",
                "nome_projeto": "",
                "valor_repassado": "",
                "valor_global": "R$ 1.291.050,00",
                "objeto": 'Execução do projeto "PROJETO DESFILE DA INDEPENDÊNCIA 2025", por meio de ações formativas, conforme plano de trabalho.',
                "data_inicio": "05/09/2025",
                "data_finalizacao": "13/10/2025",
                "justificativa": "O projeto visa promover a valorização cívica, cultural e social por meio do Desfile da Independência, fortalecendo a integração entre instituições militares, civis e a comunidade, fomentando práticas formativas e educativas que reforçam o sentimento de pertencimento e cidadania no Estado do Amapá.",
                "dados_orcamentarios": "UG: 340101 – Polícia Militar do Amapá · Programa de Trabalho: 1341010612200062277 · Natureza da Despesa: 335041 · Fonte: 500 · Valor: R$ 1.291.050,00",
                "documento_link": "https://institutomeiodomundo.org/transparencia/wp-content/uploads/2025/09/TERMO-DE-FOMENTO_PMAP-X-IMM-2025-1.pdf",
                "documento_label": "⬇️ TERMO DE FOMENTO – PMAP X IMM 2025 (PDF)",
                "ordem": 2,
            },
            {
                "titulo": "FÉRIAS SOLIDÁRIAS",
                "subtitulo": "005/2025 – SEAS",
                "status": "FINALIZADO",
                "icone": "🌴",
                "valor": "R$ 1.490.000,00",
                "instrumento": "005/2025 – SEAS",
                "recurso_financeiro": "R$ 1.490.000,00",
                "fonte_recurso_estadual": "500",
                "fonte_recurso_federal": "N/S",
                "autoria_emenda": "Emenda Parlamentar Impositiva nº 10250",
                "nome_projeto": "",
                "valor_repassado": "",
                "valor_global": "R$ 1.490.000,00",
                "objeto": 'Execução do Projeto Social "FÉRIAS SOLIDÁRIAS", visando assegurar direitos de pessoas em situação de risco e vulnerabilidade social, promovendo segurança alimentar, bem-estar e inclusão social durante o período de férias em comunidades carentes do Estado do Amapá.',
                "data_inicio": "14/09/2025",
                "data_finalizacao": "31/12/2025",
                "justificativa": "O projeto visa assegurar suporte nutricional e promover inclusão social e bem-estar para famílias em vulnerabilidade durante o período de férias, atendendo comunidades carentes do Estado do Amapá.",
                "dados_orcamentarios": "UG: 550301 – SEAS · Programa de Trabalho: 0077 · Ação: 2345 – Rede Socioassistencial / SUAS · Natureza da Despesa: 3.3.50.43 – Subvenções Sociais · Fonte: 500 · Valor: R$ 1.490.000,00",
                "documento_link": "https://institutomeiodomundo.org/transparencia/wp-content/uploads/2025/12/TERMO_DE_FOMENTO_-_005-2025-SEAS_-_INSTITUTO_MEIO_DO_MUNDO_assinado.pdf",
                "documento_label": "⬇️ TERMO DE FOMENTO 005/2025 – SEAS (PDF)",
                "ordem": 3,
            },
            {
                "titulo": "SHOW MUSICAL 4 CANTOS DA FLORESTA",
                "subtitulo": "014/2025 – SECULT",
                "status": "EM_ANDAMENTO",
                "icone": "🎶",
                "valor": "R$ 100.000,00",
                "instrumento": "014/2025 – SECULT",
                "recurso_financeiro": "R$ 100.000,00",
                "fonte_recurso_estadual": "500",
                "fonte_recurso_federal": "N/S",
                "autoria_emenda": "Emenda Parlamentar nº I0100 – Dep. Jack JK",
                "nome_projeto": "",
                "valor_repassado": "",
                "valor_global": "R$ 100.000,00",
                "objeto": 'Execução do Projeto "SHOW MUSICAL 4 CANTOS DA FLORESTA", por meio de ações culturais, conforme plano de trabalho.',
                "data_inicio": "08/08/2025",
                "data_finalizacao": "15/12/2025",
                "justificativa": 'Promover ações culturais por meio do projeto "Show Musical 4 Cantos da Floresta", alcançando a população amapaense com atividades artístico-culturais previstas no plano de trabalho.',
                "dados_orcamentarios": "UG: 380101 – SECULT · Programa de Trabalho: 13.392.0059.2202 – Projetos e Produções/Eventos da Cultura Popular/Tradicionais do Estado do Amapá · Natureza da Despesa: 33.50.43 – Subvenções Sociais · Fonte: 500 · Plano Orçamentário: 000001 · Cadastro SIAFE/AP: 250127 · Nota de Empenho: 2025NE00541 – 07/08/2025 · Valor: R$ 100.000,00",
                "ordem": 4,
            },
            {
                "titulo": 'ESPETÁCULO TEATRAL "O CORPO DE CRISTO – ELE RESSUSCITOU"',
                "subtitulo": "002/2025 – SECULT",
                "status": "FINALIZADO",
                "icone": "🎭",
                "valor": "R$ 69.000,00",
                "instrumento": "002/2025 – SECULT",
                "recurso_financeiro": "R$ 69.000,00",
                "fonte_recurso_estadual": "500",
                "fonte_recurso_federal": "N/S",
                "autoria_emenda": "Não se aplica (recurso direto da SECULT)",
                "nome_projeto": "",
                "valor_repassado": "",
                "valor_global": "R$ 69.000,00",
                "ordem": 5,
            },
            {
                "titulo": "CALÇOENE VERÃO 2025",
                "subtitulo": "005/2025-SECULT",
                "status": "FINALIZADO",
                "icone": "🏖️",
                "valor": "R$ 267.000,00",
                "instrumento": "005/2025-SECULT",
                "recurso_financeiro": "R$ 267.000,00",
                "fonte_recurso_estadual": "500",
                "fonte_recurso_federal": "N/S",
                "autoria_emenda": "Processo Administrativo nº 0054.1402.2361.0007/2025 – URDD/SECULT",
                "nome_projeto": "",
                "valor_repassado": "",
                "valor_global": "R$ 267.000,00",
                "ordem": 6,
            },
            {
                "titulo": "V CORRIDA DE RUA DA POLÍCIA CIVIL DO AMAPÁ",
                "subtitulo": "014/2025 – SEDEL",
                "status": "FINALIZADO",
                "icone": "🚓",
                "valor": "R$ 969.185,00",
                "instrumento": "014/2025 – SEDEL",
                "recurso_financeiro": "R$ 969.185,00",
                "fonte_recurso_estadual": "500",
                "fonte_recurso_federal": "N/S",
                "autoria_emenda": "Emenda Parlamentar Impositiva I0179 – Dep. Estadual",
                "nome_projeto": "",
                "valor_repassado": "",
                "valor_global": "R$ 969.185,00",
                "ordem": 7,
            },
            {
                "titulo": "I CORRIDA DA VISIBILIDADE FEMININA EM SANTANA",
                "subtitulo": "Termo de Fomento nº 008/2025 SEDEL-GEA",
                "status": "FINALIZADO",
                "icone": "👩",
                "valor": "R$ 350.000,00",
                "instrumento": "Termo de Fomento nº 008/2025 SEDEL-GEA",
                "recurso_financeiro": "R$ 350.000,00",
                "fonte_recurso_estadual": "500",
                "fonte_recurso_federal": "N/S",
                "autoria_emenda": "Emenda Parlamentar Impositiva",
                "nome_projeto": "",
                "valor_repassado": "",
                "valor_global": "R$ 350.000,00",
                "ordem": 8,
            },
            {
                "titulo": "NATAL SOLIDÁRIO – Bairro das Pedrinhas 2024",
                "subtitulo": "Termo de Fomento 021/2024 – SEAS",
                "status": "FINALIZADO",
                "icone": "🎄",
                "valor": "R$ 250.000,00",
                "instrumento": "Termo de Fomento 021/2024 – SEAS",
                "recurso_financeiro": "R$ 250.000,00",
                "fonte_recurso_estadual": "500",
                "fonte_recurso_federal": "N/S",
                "autoria_emenda": "Emenda Parlamentar Código 10493",
                "nome_projeto": "NATAL SOLIDÁRIO NO BAIRRO DAS PEDRINHAS",
                "valor_repassado": "",
                "valor_global": "R$ 250.000,00",
                "objeto": 'Execução do Projeto "NATAL SOLIDÁRIO NO BAIRRO DAS PEDRINHAS", com ações de distribuição de alimentos e atividades culturais e recreativas para as crianças.',
                "data_inicio": "28/11/2024",
                "data_finalizacao": "31/01/2025",
                "justificativa": "O projeto visa promover um Natal com dignidade e inclusão para as famílias do Bairro das Pedrinhas, por meio de ações que envolvem distribuição de alimentos e atividades culturais para as crianças.",
                "documento_link": "https://institutomeiodomundo.org/transparencia/wp-content/uploads/2025/02/Termo-de-Fomento-021-2024-SEAS.pdf",
                "documento_label": "⬇️ TERMO DE FOMENTO 021/2024 – SEAS (PDF)",
                "ordem": 9,
            },
            {
                "titulo": "CONEXÃO AMAZÔNIA",
                "subtitulo": "037/2024 – SECULT",
                "status": "FINALIZADO",
                "icone": "🌿",
                "valor": "R$ 251.200,00",
                "instrumento": "037/2024 – SECULT",
                "recurso_financeiro": "R$ 251.200,00",
                "fonte_recurso_estadual": "N/S",
                "fonte_recurso_federal": "706",
                "autoria_emenda": "Camilo Capiberibe",
                "nome_projeto": "CONEXÃO AMAZÔNIA",
                "valor_repassado": "",
                "valor_global": "R$ 251.200,00",
                "objeto": 'Execução do Projeto "CONEXÃO AMAZÔNIA", com objetivo de ampliar o acesso às políticas públicas culturais por meio da democratização e difusão cultural no Amapá, fomentando o trabalho artístico e a divulgação da produção musical local.',
                "data_inicio": "11/12/2024",
                "data_finalizacao": "31/01/2025",
                "justificativa": "O projeto Conexão Amazônia visa democratizar o acesso à cultura, valorizar a música produzida no Amapá e fomentar a circulação de artistas locais, consolidando a base cultural do estado.",
                "dados_orcamentarios": "UG: 380101 (SECULT) · Programa de Trabalho: 13.392.0059.2202 – Valorização da Cultura Popular, Criativa e do Patrimônio Histórico-Artístico e Cultural do Estado do Amapá · Natureza da Despesa: 3.3.50.41 – Contribuições · Fonte: 706 – Transferência Especial da União · SIAFE/AP: 240281 · 2024NE00747 de 05/12/2024",
                "documento_link": "https://institutomeiodomundo.org/transparencia/wp-content/uploads/2025/05/Termo-de-Fomento-037-2024-SECULT.pdf",
                "documento_label": "⬇️ TERMO DE FOMENTO 037/2024 – SECULT (PDF)",
                "ordem": 10,
            },
        ]

        projetos_criados = 0
        projetos_atualizados = 0
        for item in projetos:
            projeto, criado = Projeto.objects.update_or_create(
                titulo=item["titulo"],
                defaults=item,
            )
            if criado:
                projetos_criados += 1
            else:
                projetos_atualizados += 1
            self.stdout.write(f"OK(projeto): {projeto.titulo}")

        self.stdout.write(
            self.style.SUCCESS(
                f"Seed de projetos concluído. Criados: {projetos_criados}. Atualizados: {projetos_atualizados}.",
            ),
        )
