# Generated by Django 6.0.2 on 2026-02-25 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeGestora',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nome', models.CharField(max_length=128)),
                ('sigla', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=32, unique=True)),
                ('nome', models.CharField(max_length=128)),
                ('cargo', models.CharField(max_length=64)),
                ('vinculo', models.CharField(choices=[('EFETIVO', 'Efetivo'), ('COMISSIONADO', 'Comissionado'), ('CLT', 'CLT'), ('TEMPORARIO', 'Temporário'), ('ESTAGIARIO', 'Estagiário')], max_length=16)),
                ('remuneracao_bruta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descontos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('competencia', models.CharField(max_length=16)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidores', to='core.unidadegestora')),
            ],
        ),
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=32, unique=True)),
                ('objeto', models.CharField(max_length=256)),
                ('modalidade', models.CharField(choices=[('PREGAO_ELETRONICO', 'Pregão Eletrônico'), ('TOMADA_PRECOS', 'Tomada de Preços'), ('CONCORRENCIA', 'Concorrência'), ('DISPENSA', 'Dispensa'), ('INEXIGIBILIDADE', 'Inexigibilidade')], max_length=24)),
                ('status', models.CharField(choices=[('PUBLICADA', 'Publicada'), ('EM_ANDAMENTO', 'Em Andamento'), ('HOMOLOGADA', 'Homologada'), ('CANCELADA', 'Cancelada'), ('SUSPENSA', 'Suspensa'), ('REVOGADA', 'Revogada')], max_length=16)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_abertura', models.DateTimeField()),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licitacoes', to='core.unidadegestora')),
            ],
        ),
        migrations.CreateModel(
            name='EsicPedido',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('protocolo', models.CharField(max_length=32, unique=True)),
                ('tipo', models.CharField(choices=[('PEDIDO_ACESSO', 'Pedido de Acesso à Informação'), ('RECLAMACAO', 'Reclamação'), ('DENUNCIA', 'Denúncia'), ('SUGESTAO', 'Sugestão'), ('ELOGIO', 'Elogio')], max_length=16)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em Análise'), ('RESPONDIDO', 'Respondido'), ('INDEFERIDO', 'Indeferido'), ('ARQUIVADO', 'Arquivado')], max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('prazo', models.DateTimeField()),
                ('resposta', models.TextField(blank=True, null=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.unidadegestora')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32)),
                ('descricao', models.CharField(max_length=128)),
                ('categoria', models.CharField(choices=[('PESSOAL', 'Pessoal'), ('CUSTEIO', 'Custeio'), ('INVESTIMENTO', 'Investimento'), ('TRANSFERENCIA', 'Transferência')], max_length=16)),
                ('dotacao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('empenhado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('liquidado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exercicio', models.IntegerField()),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='core.unidadegestora')),
            ],
        ),
    ]
