# Generated by Django 6.0.2 on 2026-02-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esicpedido',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='esic_anexos/'),
        ),
    ]
