# Generated by Django 6.0.2 on 2026-02-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_esicpedido_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalInformacao',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('secao', models.CharField(choices=[('FINANCEIROS', 'Relatórios Financeiros'), ('PRESTACAO', 'Prestação de Contas'), ('CONTRATACOES', 'Contratações'), ('POLITICAS', 'Políticas e Regulamentos')], max_length=20)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['secao', 'ordem', 'titulo'],
            },
        ),
    ]
