# Generated by Django 6.0.2 on 2026-02-26 00:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portalinformacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='esicpedido',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='portalinformacao',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unidadegestora',
            name='id',
            field=models.CharField(default=core.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
