# Generated by Django 6.0.2 on 2026-03-10

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_portalinformacao_arquivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                ("id", models.CharField(default=core.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("EM_ANDAMENTO", "Em Andamento"), ("FINALIZADO", "Finalizado")], max_length=16)),
                ("icone", models.CharField(default="📌", max_length=8)),
                ("titulo", models.CharField(max_length=255)),
                ("subtitulo", models.CharField(max_length=255)),
                ("valor", models.CharField(max_length=40)),
                ("instrumento", models.CharField(max_length=255)),
                ("recurso_financeiro", models.CharField(blank=True, max_length=64)),
                ("fonte_recurso_estadual", models.CharField(blank=True, max_length=64)),
                ("fonte_recurso_federal", models.CharField(blank=True, max_length=64)),
                ("autoria_emenda", models.TextField(blank=True)),
                ("nome_projeto", models.CharField(blank=True, max_length=255)),
                ("valor_repassado", models.CharField(blank=True, max_length=64)),
                ("valor_global", models.CharField(blank=True, max_length=64)),
                ("objeto", models.TextField(blank=True)),
                ("data_inicio", models.CharField(blank=True, max_length=64)),
                ("data_finalizacao", models.CharField(blank=True, max_length=64)),
                ("justificativa", models.TextField(blank=True)),
                ("dados_orcamentarios", models.TextField(blank=True)),
                ("documento_link", models.URLField(blank=True, null=True)),
                ("documento_label", models.CharField(blank=True, max_length=200)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["ordem", "-criado_em"],
            },
        ),
    ]

