"""Django settings for portal_transparencia project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from secrets import token_urlsafe
from urllib.parse import quote_plus

from django.core.exceptions import ImproperlyConfigured

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover
    load_dotenv = None

try:
    import dj_database_url
except ImportError:  # pragma: no cover
    dj_database_url = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
if load_dotenv is not None:
    load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


def _env_int(name, default=0):
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError:
        return default


def _compose_database_url_from_parts():
    host = os.getenv("DB_HOST")
    name = os.getenv("DB_NAME")
    user = os.getenv("DB_USER")
    password = os.getenv("DB_PASSWORD")
    if not all([host, name, user, password]):
        return None

    port = os.getenv("DB_PORT", "5432")
    sslmode = os.getenv("DB_SSLMODE", "require")
    return (
        f"postgresql://{quote_plus(user)}:{quote_plus(password)}@{host}:{port}/{name}"
        f"?sslmode={sslmode}"
    )


# SECURITY WARNING: don't run with debug turned on in production!
# Default local (safe for dev commands without .env). Production must set DJANGO_DEBUG=false.
_DEFAULT_DEBUG = any(
    cmd in sys.argv for cmd in ("runserver", "test", "check", "makemigrations", "showmigrations", "shell")
)
DEBUG = _env_bool("DJANGO_DEBUG", default=_DEFAULT_DEBUG)
ALLOW_PUBLIC_REGISTRATION = _env_bool("ALLOW_PUBLIC_REGISTRATION", default=DEBUG)
IS_VERCEL = os.getenv("VERCEL") == "1"
VERCEL_ENV = os.getenv("VERCEL_ENV", "").strip().lower()

# SECURITY WARNING: keep the secret key used in production secret!
_SECRET_KEY_ENV = os.getenv("DJANGO_SECRET_KEY")
if _SECRET_KEY_ENV:
    SECRET_KEY = _SECRET_KEY_ENV
else:
    if not DEBUG and not (IS_VERCEL and VERCEL_ENV == "preview"):
        raise ImproperlyConfigured("DJANGO_SECRET_KEY obrigatorio em producao.")
    SECRET_KEY = token_urlsafe(64)

_default_allowed_hosts = "localhost,127.0.0.1,testserver"
if IS_VERCEL and VERCEL_ENV == "preview":
    _default_allowed_hosts = f"{_default_allowed_hosts},.vercel.app"

_allowed_hosts_raw = os.getenv("DJANGO_ALLOWED_HOSTS", _default_allowed_hosts)
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts_raw.split(",") if host.strip()]
if (
    not DEBUG
    and not (IS_VERCEL and VERCEL_ENV == "preview")
    and set(ALLOWED_HOSTS).issubset({"localhost", "127.0.0.1", "testserver"})
):
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS obrigatorio em producao.",
    )

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

if IS_VERCEL:
    _vercel_url = os.getenv("VERCEL_URL", "")
    _vercel_branch_url = os.getenv("VERCEL_BRANCH_URL", "")
    _vercel_project_url = os.getenv("VERCEL_PROJECT_PRODUCTION_URL", "")
    for _vurl in (_vercel_url, _vercel_branch_url, _vercel_project_url):
        if _vurl:
            _origin = f"https://{_vurl}" if not _vurl.startswith("https://") else _vurl
            if _origin not in CSRF_TRUSTED_ORIGINS:
                CSRF_TRUSTED_ORIGINS.append(_origin)
    if not any(".vercel.app" in o for o in CSRF_TRUSTED_ORIGINS):
        CSRF_TRUSTED_ORIGINS.append("https://*.vercel.app")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = _env_bool(
    "DJANGO_SECURE_SSL_REDIRECT",
    default=False,
)
SESSION_COOKIE_SECURE = _env_bool(
    "DJANGO_SESSION_COOKIE_SECURE",
    default=not DEBUG,
)
CSRF_COOKIE_SECURE = _env_bool(
    "DJANGO_CSRF_COOKIE_SECURE",
    default=not DEBUG,
)
SECURE_HSTS_SECONDS = _env_int(
    "DJANGO_SECURE_HSTS_SECONDS",
    default=31536000 if not DEBUG else 0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=not DEBUG,
)
SECURE_HSTS_PRELOAD = _env_bool(
    "DJANGO_SECURE_HSTS_PRELOAD",
    default=not DEBUG,
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "core",
]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "register": os.getenv("REGISTER_THROTTLE_RATE", "5/hour"),
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "portal_transparencia.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "portal_transparencia.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 30,
        },
    },
}

DATABASE_URL = os.getenv("DATABASE_URL") or _compose_database_url_from_parts()
if DATABASE_URL:
    if not DEBUG and DATABASE_URL.startswith("sqlite"):
        raise ImproperlyConfigured("SQLite nao e permitido em producao. Use PostgreSQL em DATABASE_URL.")
    if dj_database_url is None:
        raise ImproperlyConfigured(
            "DATABASE_URL definido, mas pacote dj-database-url nao esta instalado.",
        )
    DATABASES["default"] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=not DEBUG,
    )
elif not DEBUG:
    allow_vercel_sqlite_fallback = _env_bool("ALLOW_VERCEL_SQLITE_FALLBACK", default=IS_VERCEL)
    if allow_vercel_sqlite_fallback:
        sqlite_path = Path(os.getenv("DJANGO_SQLITE_PATH", "/tmp/vercel.sqlite3"))
        DATABASES["default"] = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": sqlite_path,
            "OPTIONS": {
                "timeout": 30,
            },
        }
        os.environ["DJANGO_SQLITE_PATH"] = str(sqlite_path)
    else:
        raise ImproperlyConfigured(
            "DATABASE_URL obrigatorio em producao. "
            "Configure um PostgreSQL (ex: postgresql://usuario:senha@host:5432/banco).",
        )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
WHITENOISE_USE_FINDERS = False

if IS_VERCEL:
    # In Vercel serverless, we serve static files directly from the bundled
    # source folder to avoid requiring a separate collectstatic step.
    STATIC_ROOT = BASE_DIR / "static"
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
    WHITENOISE_USE_FINDERS = True

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if IS_VERCEL:
    MEDIA_ROOT = Path(os.getenv("DJANGO_MEDIA_ROOT", "/tmp/django-media"))
    MEDIA_ROOT.mkdir(parents=True, exist_ok=True)

# Cloudflare R2 / S3-compatible storage for uploaded files
_R2_ACCESS_KEY = os.getenv("R2_ACCESS_KEY_ID", "")
_R2_SECRET_KEY = os.getenv("R2_SECRET_ACCESS_KEY", "")
_R2_BUCKET = os.getenv("R2_BUCKET_NAME", "")
_R2_ENDPOINT = os.getenv("R2_ENDPOINT_URL", "")
_R2_PUBLIC_DOMAIN = os.getenv("R2_PUBLIC_DOMAIN", "")  # e.g. pub-xxx.r2.dev

if _R2_ACCESS_KEY and _R2_SECRET_KEY and _R2_BUCKET and _R2_ENDPOINT:
    _r2_use_public = bool(_R2_PUBLIC_DOMAIN)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": _R2_ACCESS_KEY,
                "secret_key": _R2_SECRET_KEY,
                "bucket_name": _R2_BUCKET,
                "endpoint_url": _R2_ENDPOINT,
                "region_name": "auto",
                "default_acl": None,
                "querystring_auth": not _r2_use_public,
                "querystring_expire": 604800,  # 7 days (boto3 max)
                "file_overwrite": False,
                **({"custom_domain": _R2_PUBLIC_DOMAIN} if _r2_use_public else {}),
            },
        },
        "staticfiles": {
            "BACKEND": STATICFILES_STORAGE,
        },
    }
    if _r2_use_public:
        MEDIA_URL = f"https://{_R2_PUBLIC_DOMAIN}/"
    else:
        MEDIA_URL = f"{_R2_ENDPOINT}/{_R2_BUCKET}/"
